version: '3.8'
services:
  mysql_database:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: skillShare_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./SkillShare
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/skillShare_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    ports:
      - "3600:3600"
    depends_on:
      - mysql_database

volumes:
  mysql_data: